#!/bin/bash
export PARSIFAL2_home=/home/riccardo/GTS_PARSIFAL/Git_repository/PARSIFAL_test
export PARSIFAL2=/home/riccardo/GTS_PARSIFAL/Git_repository/PARSIFAL_test
export parsifal2=/home/riccardo/GTS_PARSIFAL/Git_repository/PARSIFAL_test
alias  PARSIFAL2='/PARSIFAL2.sh'
alias  parsifal2='PARSIFAL2'
export PARSIFAL2_data=/home/riccardo/GTS_PARSIFAL/Git_repository/PARSIFAL_test/data
export exe_parsifal2=/home/riccardo/GTS_PARSIFAL/Git_repository/PARSIFAL_test/PARSIFAL2.sh
function cd_parsifal(){
cd ;
}
